spring.application.name=payment-orchestration
server.port=8080

user.timezone=Asia/Kolkata

spring.datasource.url=jdbc:sqlserver://localhost;databaseName=db1;integratedSecurity=false;TrustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Abcd@1234
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.JDBC.lob.non_contextual_creation=true


spring.redis.host=localhost
spring.redis.port=6379
spring.redis.timeout=2000ms

idempotency.ttl-seconds=86400
idempotency.in-flight-ttl-seconds=60

providers.providerA.id=providerA
providers.providerA.latency-ms=25

providers.providerB.id=providerB
providers.providerB.latency-ms=40
#providers.providerB.fail-on-currencies=XOF

routing.rules-json=[{"currency": "EUR","amountMax": 500.00,"providers": ["providerA"]},{"currency": "INR","amountMax": 1000.00,"providers": ["providerB"]}]


logging.level.com.yuno.assignment=INFO
logging.level.org.hibernate.SQL=WARN
